import {supabase} from './supabase';
import type {Difficulty,Problem,Profile,Solution} from '../types';
export async function getProfile(id:string){if(!supabase)return null; const {data}=await supabase.from('profiles').select('*').eq('id',id).single(); return data as Profile|null}
export async function getProblems(){if(!supabase)return []; const {data,error}=await supabase.from('problems').select('*, author:profiles!problems_author_id_fkey(*)').order('created_at',{ascending:false}).limit(50); if(error)throw error; return (data??[]) as Problem[]}
export async function getProblem(id:string){if(!supabase)return null; const {data,error}=await supabase.from('problems').select('*, author:profiles!problems_author_id_fkey(*)').eq('id',id).single(); if(error)throw error; return data as Problem}
export async function getSolutions(problemId:string){if(!supabase)return []; const {data,error}=await supabase.from('solutions').select('*, author:profiles!solutions_author_id_fkey(*)').eq('problem_id',problemId).order('is_accepted',{ascending:false}).order('created_at',{ascending:true}); if(error)throw error; return (data??[]) as Solution[]}
export async function createProblem(title:string,description:string,difficulty:Difficulty,tags:string[]){if(!supabase)throw new Error('Supabase is not configured'); const {data,error}=await supabase.rpc('create_problem',{p_title:title,p_description:description,p_difficulty:difficulty,p_technology_slugs:tags}); if(error)throw error; return data as string}
export async function createSolution(problemId:string,body:string){if(!supabase)throw new Error('Supabase is not configured'); const {data,error}=await supabase.rpc('create_solution',{p_problem_id:problemId,p_body:body}); if(error)throw error; return data as string}
export async function acceptSolution(problemId:string,solutionId:string){if(!supabase)throw new Error('Supabase is not configured'); const {error}=await supabase.rpc('accept_solution',{p_problem_id:problemId,p_solution_id:solutionId}); if(error)throw error}
export async function toggleBookmark(problemId:string){if(!supabase)throw new Error('Supabase is not configured'); const {data,error}=await supabase.rpc('toggle_bookmark',{p_problem_id:problemId}); if(error)throw error; return Boolean(data)}
export async function recordView(problemId:string){if(!supabase)return; await supabase.rpc('record_problem_view',{p_problem_id:problemId,p_viewer_key:crypto.randomUUID()})}
